# Generated by Django 4.2.13 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniblocks',
            name='image',
            field=models.ImageField(upload_to='mini-blocks'),
        ),
    ]
