# Generated by Django 4.2.13 on 2024-08-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_miniblocks_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miniblocks',
        ),
    ]
