# Generated by Django 4.2.13 on 2024-08-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_miniblocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='mini-blocks')),
            ],
            options={
                'verbose_name': 'Mini Block',
                'verbose_name_plural': 'Mini Blocks',
            },
        ),
        migrations.CreateModel(
            name='TreeBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='tree-blocks')),
            ],
            options={
                'verbose_name': 'Tree Block',
                'verbose_name_plural': 'Tree Blocks',
            },
        ),
    ]
