# Generated by Django 4.2.13 on 2024-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_about_blog_contact_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('phone_class', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('email_class', models.CharField(max_length=255)),
                ('location_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Info Section',
                'verbose_name_plural': 'Info Sections',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
        migrations.AlterField(
            model_name='miniblocks',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
