# Generated by Django 4.2.13 on 2024-11-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_infosection_socials_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='text',
        ),
        migrations.AddField(
            model_name='footertext',
            name='link_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footertext',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footertext',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footertext',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
