# Generated by Django 4.2.13 on 2024-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_footertext_text_footertext_link_name1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertext',
            old_name='link_name1',
            new_name='link_name',
        ),
    ]
