# Generated by Django 4.2.13 on 2024-11-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_link_name1_footertext_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonial Main',
                'verbose_name_plural': 'Testimonial Main',
            },
        ),
        migrations.AddField(
            model_name='headertext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='header_text'),
        ),
        migrations.AlterField(
            model_name='headertext',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headertext',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
