# Generated by Django 4.2.13 on 2024-11-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='namber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
