# Generated by Django 4.2.13 on 2024-11-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_message_namber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='namber',
            new_name='number',
        ),
    ]
